filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json
    json.keys_under_root: true
    json.add_error_key: true
    processors:
      - add_fields:
          target: 'wazuh'
          fields:
            source: 'wazuh-manager'
            pipeline: 'alerts'

output.elasticsearch:
  hosts: ["wazuh-elasticsearch:9200"]
  protocol: "http"
  # For Elastic 7.x with security disabled, no auth needed
  # username: "elastic"
  # password: "changeme"

setup.template.name: "wazuh-alerts"
setup.template.pattern: "wazuh-alerts-*"
setup.ilm.enabled: false
strict.perms: false

logging.level: info
logging.json: true

